// <auto-generated />
using System;
using ExtractHUContext.WriteSide.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExtractHUContext.WriteSide.Infrastructure.Migrations
{
    [DbContext(typeof(QuantumHUDbContext))]
    [Migration("20260113163046_AddHUExtractionFields")]
    partial class AddHUExtractionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quantum_hu_context")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExtractHUContext.WriteSide.Infrastructure.Persistence.Ef.MedicalStudyEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExtractionCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ExtractionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtractionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("MaxHU")
                        .HasColumnType("double precision");

                    b.Property<double?>("MeanHU")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinHU")
                        .HasColumnType("double precision");

                    b.Property<double?>("StandardDeviation")
                        .HasColumnType("double precision");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VoxelCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Medical_Studies", "quantum_hu_context");
                });
#pragma warning restore 612, 618
        }
    }
}
